// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/0xirvan/tdl-svelte-go/server/internal/adapter/config"
	"github.com/0xirvan/tdl-svelte-go/server/internal/adapter/delivery/http"
	"github.com/0xirvan/tdl-svelte-go/server/internal/adapter/persistence/inmemory"
	"github.com/0xirvan/tdl-svelte-go/server/internal/core/usecase/todo"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeHTTPApp(ctx context.Context, cfg *config.AppContainer) (*HTTPApp, error) {
	configHTTP := ProvideHTTPConfig(cfg)
	router := http.NewRouter(configHTTP)
	todoRepository := inmemory.NewTodoRepository()
	service := todo.NewService(todoRepository)
	todoHandler := http.NewTodoHandler(service)
	httpApp := NewHTTPApp(router, cfg, todoHandler)
	return httpApp, nil
}

// wire.go:

func ProvideHTTPConfig(cfg *config.AppContainer) *config.HTTP {
	return cfg.HTTP
}

var todoSet = wire.NewSet(inmemory.NewTodoRepository, todo.NewService, http.NewTodoHandler)
