// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/0xirvan/tdl-svelte-go/server/internal/adapter/config"
	"github.com/0xirvan/tdl-svelte-go/server/internal/adapter/delivery/http"
	"github.com/0xirvan/tdl-svelte-go/server/internal/adapter/persistence/inmemory"
	"github.com/0xirvan/tdl-svelte-go/server/internal/core/usecase/todo"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeHTTPApp(ctx context.Context, cfg *config.AppContainer) (*HTTPApp, error) {
	configHTTP := ProvideHTTPConfig(cfg)
	todoRepository := inmemory.NewTodoRepository()
	service := todo.NewService(todoRepository)
	todoHandler := http.NewTodoHandler(service)
	router := http.NewRouter(configHTTP, todoHandler)
	httpApp := NewHTTPApp(router, cfg)
	return httpApp, nil
}

// wire.go:

func ProvideHTTPConfig(cfg *config.AppContainer) *config.HTTP {
	return cfg.HTTP
}

// Infrastructure providers
var infraSet = wire.NewSet(
	ProvideHTTPConfig,
)

// Repository layer
var repositorySet = wire.NewSet(inmemory.NewTodoRepository)

// Use case layer
var useCaseSet = wire.NewSet(todo.NewService)

// Delivery layer
var deliverySet = wire.NewSet(http.NewTodoHandler, http.NewRouter)

// All sets
var appSet = wire.NewSet(
	infraSet,
	repositorySet,
	useCaseSet,
	deliverySet,
	NewHTTPApp,
)
